const storydb = {
    "Chapter1":{
        1:["banner_cha_s.png","The Archangel Lucifer defied the will of God with the sin of Pride, and was banished from Heaven. She fell down into Hell, and her power was sealed by the Seven Mortal Sins. This was how Lucifer lost everything… But with the help of her admirer Leviathan and the high school girl Maria Totsuka, Lucifer defeated the Demon Lords and broke their seal on her. However, Lucifer would ultimately find out that the Demon Lords’ leader, Belial of Vainglory… had an underhanded dealing with Heaven and their plan to help God recreate the world anew. To keep the world from being destroyed, Lucifer partnered with the other Demon Lords… …and faced her old comrade Michael, the Archangel of Faith, on the battlefield. Although Lucifer had seemingly been defeated & killed… Maria sacrificed herself to bring back Lucifer, and the plan of Heaven was stopped. The world was saved, and God would not wipe out the innocent & regretful with Her addled binary, all-or-nothing view. After that, Lucifer became the Demon Lord of Pride, as well as the leader of the Seven Mortal Sins."],
        2:["banner_cha_s.png", "There are three different, known worlds or planes of existence in the universe: Humans live on the Surface world of Earth, God and Her Angels live & rule in Heaven, and the Demon Lords dominate Hell along with their devilish minions. Both the Angels & Demon Lords can acquire power from the pious acts & belief from humankind. With this, the Angels & the Demon Lords started to solicit from humanity over days & nights……<Tokyo, night, near the alleyways>"],
        3:["lucifer0-00.png", "Heheheh... the Earth is such a nice place... everywhere I look, sins are waiting to be committed."],
        4:["gamepic_cha01.png","The Demon Lord of Pride, Lucifer defied the will of God and was banished from Heaven. Existing as a fallen angel ever since, she saved all of humanity from being wiped out by God’s arbitrariness & binary thinking. As a result, all her ties to Heaven disappeared, and she became the now-current leader of the Seven Mortal Sins. While she acts arrogant and looks down on people a lot, Lucifer is secretly a naïve, straightforward & spoiled girl of a lady, one who is easily charmed by a simple compliment."],
        5:["levi0-05.png","Sis, look! The Envy coming off that man feels delicious~♪"],
        6:["banner_cha_s.png","The Demon Lord of Envy, Leviathan has a secret crush on Lucifer atop a strong, fanatical obsession with her. She has the ability to manipulate water as well as being able to summon & command marine creatures. Also possessing great culinary talent, Leviathan is willing to do anything for those she loves, but whenever she gets upset, she will beat up her subordinate Behemoth."],
        7:["maria0-09.png","Are you recruiting followers today, too? I think we have enough followers already…"],
        8:["maria0-09.png","A student in Miracle Women's Academy and Lucifer's strongest believer, Maria leads the cleaning crew of her class. Considerate & mature, she always looks out for others. After the coincidental encounter with Lucifer when she crashed down at the school church after being cast from Heaven, Maria ended up being involved with the relentless schemes around the head throne of the Seven Mortal Sins, forced to travel with Lucifer & Leviathan on their adventure."],
        9:["lucifer0-09.png","What the Hell are you talking about, Maria?"],
        10:["lucifer0-02.png","Only when everyone in the world worships I, Lucifer, the Demon Lord ofPride, will that be enough for me!"],
        11:["lucifer0-03.png","Don’t you understand? If mankind wants to be saved, then we Demon Lords must grow in strength!"],
        12:["levi0-03.png","Exactly! That’s right! God and Her Angels are all itching for an excuse to destroy your world and reenact Creation all over again!"],
        13:["levi0-11.png","Only we Demon Lords of Hell can possibly stand against them!"],
        14:["lucifer0-09.png"," I guess you humans might not have realized this yet…"],
        15:["lucifer0-06.png","…But an all-out war between Heaven & Hell can happen at any time."],
        16:["maria0-10.png","Well, come to think of it, I’m hearing a lot of rumors about incidents where people have been “spirited away” lately."],
        17:["levi0-07.png","What’s that?"],
        18:["maria0-06.png","It’s just something I overheard a classmate saying. I really don’t know the exact details…It’s just something I overheard a classmate saying. I really don’t know the exact details…"],
        19:["maria0-12.png"," …But apparently, some people are being drawn in by strange advertisements on late-night broadcast, and end up getting sucked into another world."],
        20:["levi0-09.png","Whoa, that sounds pretty crazy!"],
        21:["maria0-10.png","Oh no, it’s already this late! I need to head home!"],
        22:["maria0-02.png","Well, I’ll be going; you take care on the way back too. After maria takes her leave…"],
        23:["lucifer0-08.png","Hah… I never expected a human to ever tell a Demon Lord to “take care” like that."],
        24:["levi0-00.png","I know, right! How pointless! On the walk back…"],
        25:["maria0-02.png","‘Phew… good, we got through the day without anything bad happening.’"],
        26:["maria0-03.png","Wait, no, that’s not the takeaway from this meeting."],
        27:["maria0-08.png","Spending so much time with Lucifer and the other Demon Lords has warped my idea of what “normal” is supposed to be…’ Going around a corner, she happens upon a young girl with long, blonde hair and blue eyes dressed rather provocatively; her underwear is showing, and she is seated atop… a large, dismembered hand."],
        28:["Anastasia-04.png","Hmmm…? She’s looking around, and Maria notices that she has large, red gradient horns on her head."],
        29:["maria0-10.png"," …?!"],
        30:["Anastasia-06.png", "Where is she…?"],
        31:["maria0-06.png","‘Why is this little girl outside this late, all by herself? Does she have parents?’ She then speaks up to the girl, getting her attention. Um, excuse me… what are you doing outside all by yourself this late? Seeing Maria, and hearing her voice, the girl’s expression changes."],
        32:["Anastasia-07.png","Maria… Totsuka…!"],
        33:["maria0-10.png","?!How does this girl know my name?!"],
        34:["Anastasia-06.png","Aha,I found you at last.The key, so important to us… Just as Maria turns to sprint, a sudden bright flash dazes her…"],
        35:["maria0-12.png"," ‘What was that light… I— Oh no, I’m starting to feel a little woozy…’ That’s an understatement, as she practically faints. Whisked away from there, she wakes up in a nondescript church. ‘Where… have I been taken? And where is that little girl—‘ Her wondering stops with the appearance of two familiar faces…"],
        36:["asta0-06.png","It looks like she’s awake, Belial-sama."],
        37:["asta0-00.png","Astaroth (Melancholy) The Demon Lord of Melancholy, Astaroth has an alternative identity as a very popular musician & underground idol of the internet who makes sad songs to convey her feelings. This is due to her passive, sociophobic & negative character from having a crippling inferiority complex as well as persecutory delusions, which makes it hard for others to communicate with her. Astaroth adores Belial, the Lord of Vainglory, for always being kind to her since early times, and follows her wherever she goes out of loyalty, committed to helping her."],
        38:["belial0-00.png","Oh-hohohoho! It’s been a long time, Maria."],
        39:["belial0-00.png"," Belial (Vainglory) The Demon Lord of Vainglory, Belial comes from Hell’s prestigious Byrndale family, and was the former leader of the Seven Mortal Sins before being defeated & banished to Earth by Lucifer. Long ago, she was Satanael, the First Angel of Heaven, and had been cast down to Hell for the backfiring of her efforts to gather more followers. With a massive ego, and always bragging about things she cannot actually do, Belial is firmly a troublemaker. Even so, she is always confident, staying positive & keeping an iron will."],
        40:["maria0-10.png","Belial! Astaroth! Why are you here…?!"],
        41:["belial0-01.png","Come over here, you lot. Here she is, the key to this world… while she is human, there is angelic blood within her.Four unfamiliar faces all show up to look at her."],
        42:["thyrza0-00.png","Muhahaha…! She looks quite delicious…"],
        43:["chino0-09.png","Oh, really…? She seems like nothing but an ordinary human to me."],
        44:["sutalr0-00.png","Deep within, her power still sleeps."],
        45:["esmira0-01.png","However, the time of awakening is approaching…"],
        46:["Anastasia-09.png","Hee hee… you’re scaring Maria, gathering around her like that"],
        47:["maria0-12.png","Who are you people…? Are you demons, angels, or…?"],
        48:["belial0-00.png","Listen carefully, Maria… these people you see will change the world that currently exists."],
        49:["Anastasia-00.png","We have been reborn into this world, but not as demons or angels. If you must give us a name, then it shall be… The Third Faction. As Belial, Astaroth & this Third Faction prepare Maria for their plans, a whole day passes. The following night, back in the city of Tokyo…"],
        50:["banner_cha_s.png","The Archangel Lucifer defied the will of God with the sin of Pride, and was banished from Heaven. She fell down into Hell, and her power was sealed by the Seven Mortal Sins. This was how Lucifer lost everything… But with the help of her admirer Leviathan and the high school girl Maria Totsuka, Lucifer defeated the Demon Lords and broke their seal on her. However, Lucifer would ultimately find out that the Demon Lords’ leader, Belial of Vainglory… had an underhanded dealing with Heaven and their plan to help God recreate the world anew. To keep the world from being destroyed, Lucifer partnered with the other Demon Lords… …and faced her old comrade Michael, the Archangel of Faith, on the battlefield. Although Lucifer had seemingly been defeated & killed… Maria sacrificed herself to bring back Lucifer, and the plan of Heaven was stopped. The world was saved, and God would not wipe out the innocent & regretful with Her addled binary, all-or-nothing view. After that, Lucifer became the Demon Lord of Pride, as well as the leader of the Seven Mortal Sins."],
        51:["banner_cha_s.png", "There are three different, known worlds or planes of existence in the universe: Humans live on the Surface world of Earth, God and Her Angels live & rule in Heaven, and the Demon Lords dominate Hell along with their devilish minions. Both the Angels & Demon Lords can acquire power from the pious acts & belief from humankind. With this, the Angels & the Demon Lords started to solicit from humanity over days & nights……<Tokyo, night, near the alleyways>"],
        52:["lucifer0-00.png", "Heheheh... the Earth is such a nice place... everywhere I look, sins are waiting to be committed."],
        53:["gamepic_cha01.png","The Demon Lord of Pride, Lucifer defied the will of God and was banished from Heaven. Existing as a fallen angel ever since, she saved all of humanity from being wiped out by God’s arbitrariness & binary thinking. As a result, all her ties to Heaven disappeared, and she became the now-current leader of the Seven Mortal Sins. While she acts arrogant and looks down on people a lot, Lucifer is secretly a naïve, straightforward & spoiled girl of a lady, one who is easily charmed by a simple compliment."],
        54:["levi0-05.png","Sis, look! The Envy coming off that man feels delicious~♪"],
        55:["banner_cha_s.png","The Demon Lord of Envy, Leviathan has a secret crush on Lucifer atop a strong, fanatical obsession with her. She has the ability to manipulate water as well as being able to summon & command marine creatures. Also possessing great culinary talent, Leviathan is willing to do anything for those she loves, but whenever she gets upset, she will beat up her subordinate Behemoth."],
        56:["maria0-09.png","Are you recruiting followers today, too? I think we have enough followers already…"],
        57:["maria0-09.png","A student in Miracle Women's Academy and Lucifer's strongest believer, Maria leads the cleaning crew of her class. Considerate & mature, she always looks out for others. After the coincidental encounter with Lucifer when she crashed down at the school church after being cast from Heaven, Maria ended up being involved with the relentless schemes around the head throne of the Seven Mortal Sins, forced to travel with Lucifer & Leviathan on their adventure."],
        58:["lucifer0-09.png","What the Hell are you talking about, Maria?"],
        59:["lucifer0-02.png","Only when everyone in the world worships I, Lucifer, the Demon Lord ofPride, will that be enough for me!"],
        60:["lucifer0-03.png","Don’t you understand? If mankind wants to be saved, then we Demon Lords must grow in strength!"],
        61:["levi0-03.png","Exactly! That’s right! God and Her Angels are all itching for an excuse to destroy your world and reenact Creation all over again!"],
        62:["levi0-11.png","Only we Demon Lords of Hell can possibly stand against them!"],
        63:["lucifer0-09.png"," I guess you humans might not have realized this yet…"],
        64:["lucifer0-06.png","…But an all-out war between Heaven & Hell can happen at any time."],
        65:["maria0-10.png","Well, come to think of it, I’m hearing a lot of rumors about incidents where people have been “spirited away” lately."],
        66:["levi0-07.png","What’s that?"],
        67:["maria0-06.png","It’s just something I overheard a classmate saying. I really don’t know the exact details…It’s just something I overheard a classmate saying. I really don’t know the exact details…"],
        68:["maria0-12.png"," …But apparently, some people are being drawn in by strange advertisements on late-night broadcast, and end up getting sucked into another world."],
        69:["levi0-09.png","Whoa, that sounds pretty crazy!"],
        70:["maria0-10.png","Oh no, it’s already this late! I need to head home!"],
        71:["maria0-02.png","Well, I’ll be going; you take care on the way back too. After maria takes her leave…"],
        72:["lucifer0-08.png","Hah… I never expected a human to ever tell a Demon Lord to “take care” like that."],
        73:["levi0-00.png","I know, right! How pointless! On the walk back…"],
        74:["maria0-02.png","‘Phew… good, we got through the day without anything bad happening.’"],
        75:["maria0-03.png","Wait, no, that’s not the takeaway from this meeting."],
        76:["maria0-08.png","Spending so much time with Lucifer and the other Demon Lords has warped my idea of what “normal” is supposed to be…’ Going around a corner, she happens upon a young girl with long, blonde hair and blue eyes dressed rather provocatively; her underwear is showing, and she is seated atop… a large, dismembered hand."],
        77:["Anastasia-04.png","Hmmm…? She’s looking around, and Maria notices that she has large, red gradient horns on her head."],
        78:["maria0-10.png"," …?!"],
        79:["Anastasia-06.png", "Where is she…?"],
        80:["maria0-06.png","‘Why is this little girl outside this late, all by herself? Does she have parents?’ She then speaks up to the girl, getting her attention. Um, excuse me… what are you doing outside all by yourself this late? Seeing Maria, and hearing her voice, the girl’s expression changes."],
        81:["Anastasia-07.png","Maria… Totsuka…!"],
        82:["maria0-10.png","?!How does this girl know my name?!"],
        83:["Anastasia-06.png","Aha,I found you at last.The key, so important to us… Just as Maria turns to sprint, a sudden bright flash dazes her…"],
        84:["maria0-12.png"," ‘What was that light… I— Oh no, I’m starting to feel a little woozy…’ That’s an understatement, as she practically faints. Whisked away from there, she wakes up in a nondescript church. ‘Where… have I been taken? And where is that little girl—‘ Her wondering stops with the appearance of two familiar faces…"],
        85:["asta0-06.png","It looks like she’s awake, Belial-sama."],
        86:["asta0-00.png","Astaroth (Melancholy) The Demon Lord of Melancholy, Astaroth has an alternative identity as a very popular musician & underground idol of the internet who makes sad songs to convey her feelings. This is due to her passive, sociophobic & negative character from having a crippling inferiority complex as well as persecutory delusions, which makes it hard for others to communicate with her. Astaroth adores Belial, the Lord of Vainglory, for always being kind to her since early times, and follows her wherever she goes out of loyalty, committed to helping her."],
        87:["belial0-00.png","Oh-hohohoho! It’s been a long time, Maria."],
        88:["belial0-00.png"," Belial (Vainglory) The Demon Lord of Vainglory, Belial comes from Hell’s prestigious Byrndale family, and was the former leader of the Seven Mortal Sins before being defeated & banished to Earth by Lucifer. Long ago, she was Satanael, the First Angel of Heaven, and had been cast down to Hell for the backfiring of her efforts to gather more followers. With a massive ego, and always bragging about things she cannot actually do, Belial is firmly a troublemaker. Even so, she is always confident, staying positive & keeping an iron will."],
        89:["maria0-10.png","Belial! Astaroth! Why are you here…?!"],
        90:["belial0-01.png","Come over here, you lot. Here she is, the key to this world… while she is human, there is angelic blood within her.Four unfamiliar faces all show up to look at her."],
        91:["thyrza0-00.png","Muhahaha…! She looks quite delicious…"],
        92:["chino0-09.png","Oh, really…? She seems like nothing but an ordinary human to me."],
        93:["sutalr0-00.png","Deep within, her power still sleeps."],
        94:["esmira0-01.png","However, the time of awakening is approaching…"],
        95:["Anastasia-09.png","Hee hee… you’re scaring Maria, gathering around her like that"],
        96:["maria0-12.png","Who are you people…? Are you demons, angels, or…?"],
        97:["belial0-00.png","Listen carefully, Maria… these people you see will change the world that currently exists."],
        98:["Anastasia-00.png","We have been reborn into this world, but not as demons or angels. If you must give us a name, then it shall be… The Third Faction. As Belial, Astaroth & this Third Faction prepare Maria for their plans, a whole day passes. The following night, back in the city of Tokyo…"],
        99:["lucifer0-03.png","I’ve already searched the entire city! Something is definitely wrong. An unknown female with a leather   helmet work goggles, and a mobile workshop attached to her in the form of a mech suit interrupts."],
        100:["jacqueline-07.png","Ah, I found you at last! You’re lucifer, the Demon Lord of Pride, right?"],
        101:["levi0-01.png","Oh, and who are you?! How dare you speak to my Sis without permission!"],
        102:["jacqueline-02.png","Oh, I’m sorry, I forgot to introduce myself… my name is Jacqueline!"],
        103:["jacqueline-00.png","I’m here to deliver a letter to you."],
        104:["lucifer0-03.png","A letter, huh? Who sent this to me?"],
        105:["jacqueline-00.png","Everything will be clear once you read it."],
        106:["gamepic_cha01.png","lucifer opens it…"],
        107:["lucifer0-09.png","Let me see…"],
        108:["lucifer0-03.png","This letter… its from Belial!"],
        109:["banner_cha_s.png","She reads it off out loud…"],
        110:["belial0-02.png","Lucifer, I imagine you’re searching everywhere on Earth for that human companion of yours."],
        111:["belial0-00.png","Just the thought of how ridiculous you must look right now brings a smile to my face."],
        112:["belial0-05.png","Why is that, you wonder? Well, it’s very simple… Maria is in our hands now!"],
        113:["belial0-00.png","So, if you want her back, then come to Limbo. I can’t wait to see you again…"],
        114:["banner_cha_s.png","Understandably, Lucifer is enraged."],
        115:["lucifer0-04.png","‘Belial, that scummy bitch…!’"],
        116:["lucifer0-01.png","Jacqueline, what is Belial up to now?! You better answer me!"],
        117:["jacqueline-03.png","I apologize for the abduction of your friend… but I can't tell you anything more. It is… our destiny…!"],
        118:["lucifer0-09.png"," Oh, so you want to remain silent. Well, in that case…!"],
    },
    "Chapter2":{
    }
    
}

export default storydb;